FROM ghcr.io/autowarefoundation/autoware:20240903-devel-cuda-amd64

ENV http_proxy http://127.0.0.1:7897
ENV https_proxy http://127.0.0.1:7897

# ROS repository key expired on 2025-06-01.
# Workaround based on: https://github.com/osrf/docker_images/issues/807

# Remove existing keys / source
RUN rm /etc/apt/sources.list.d/ros2-latest.list \
  && rm /usr/share/keyrings/ros2-latest-archive-keyring.gpg

# Install the new key
RUN apt-get update \
  && apt-get install -y ca-certificates curl
RUN export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F\" '{print $4}') ;\
    curl -L -s -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo $VERSION_CODENAME)_all.deb" \
    && apt-get update \
    && apt-get install /tmp/ros2-apt-source.deb \
    && rm -f /tmp/ros2-apt-source.deb

# Download necessary packages
RUN apt-get update
# Useful tools
RUN apt-get install -y wget unzip tmux inetutils-ping curl vim
RUN python3 -m pip install gdown
RUN printf 'set-option -g default-shell /bin/bash\nset -g default-terminal "tmux-256color"' > /etc/tmux.conf
# Used by zenoh-bridge-ros2dds
RUN apt-get install -y llvm-dev libclang-dev cmake
# Used by my carla-bridge
RUN apt-get install -y ros-humble-moveit-msgs parallel
# Used by carla-sys
RUN apt-get install -y clang-12 libclang-12-dev
# Used by pyenv
RUN apt-get install -y build-essential libssl-dev zlib1g-dev \
                       libbz2-dev libreadline-dev libsqlite3-dev curl \
                       libncursesw5-dev xz-utils tk-dev libxml2-dev \
                       libxmlsec1-dev libffi-dev liblzma-dev
# Create a file to differentiate the container
RUN touch /opt/zenoh-carla-bridge

# Install python3.8.10
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get update
RUN apt-get install -y python3.8 python3.8-venv python3.8-distutils python3.8-dev
RUN ln -sf /usr/bin/python3.8 /usr/bin/python
RUN curl https://bootstrap.pypa.io/pip/3.8/get-pip.py -o get-pip.py && python get-pip.py

CMD bash
